/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "worldmanager"

dependencyResolutionManagement {
    versionCatalogs {
      create ("libs") {
            files("./gradle/libs.versions.toml")
        }
    }
}
include("worldmanager.core")
include("worldmanager.features")
include("common")