/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thebest12lines_worldmanager_util_SystemSettings */

#ifndef _Included_com_thebest12lines_worldmanager_util_SystemSettings
#define _Included_com_thebest12lines_worldmanager_util_SystemSettings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thebest12lines_worldmanager_util_SystemSettings
 * Method:    getSystemTheme
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_thebest12lines_worldmanager_util_SystemSettings_getSystemTheme
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
