name: Java CI with Code Coverage

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download Oracle JDK
      run: |
        curl -L -o jdk-21_windows-x64_bin.zip https://download.oracle.com/java/21/latest/jdk-21_windows-x64_bin.zip
        tar -xf jdk-21_windows-x64_bin.zip
        mv jdk-21 /c/Program\ Files/

    - name: Set up Oracle JDK
      run: |
        echo "JAVA_HOME=/c/Program Files/jdk-21" >> $GITHUB_ENV
        echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

    - name: Verify Java installation
      run: java -version
    # - name: Set up JDK 21
    #   uses: actions/setup-java@v2
    #   with:
    #     distribution: "temurin"
    #     java-version: '21'

    # - name: Build with Maven
    #   run: mvn clean install

    - name: Run tests with coverage
      run: mvn test jacoco:report

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./target/site/jacoco/jacoco.xml
       # fail_ci_if_error: true
        verbose: true
