name: Java CI with Code Coverage

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # Use 'temurin' distribution
        java-version: '21'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests with coverage
      run: mvn test jacoco:report

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./target/site/jacoco/jacoco.xml
        fail_ci_if_error: true
        verbose: true
